# Set of pods that are called deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    state: production
spec:
  replicas: 3 # number of pod replicas to run
  selector: # how to identify the pods managed by this deployment
    matchLabels:
      batch: myapps
  template: # template for the pods to be created
    metadata: # basic details about the object
      name: myapp-pod # name of the pod
      labels: # key-value pairs to categorize objects
        app: myapp
    spec: # complete details about that object
      containers: # list of containers in the pod
        - name: myapp-container # name of the container
          image: nginx # container image to use
          ports: # list of ports to expose from the container
            - containerPort: 80 # port number inside the container