apiVersion: v1
kind: Pod # what kind of k8 object we're working with
metadata: # basic details about the object
  name: nginx # name of the pod
  labels: # key-value pairs to categorize objects
    app: nginx
    batch: c44
spec: # complete details about that object
  containers: # list of containers in the pod
    - name: nginx # name of the container
      image: nginx # container image to use



# Set of pods that are called deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: m1-nginx
    state: production
spec:
  replicas: 3
  selector:
    matchLabels:
      batch: c44
      app: nginx
  template:
    metadata:
      labels:
        batch: c44
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx


# the router for traffic (internal)
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    batch: myserviceapp
spec:
  type: ClusterIP
  selector:
    batch: c44
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
